# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH Secrets
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          echo "User: ${{ secrets.SERVER_USER }}"
          echo "Work Dir: ${{ secrets.WORK_DIR }}"
          echo "Private Key Length: ${{ env.KEY_LENGTH }}"
        env:
          KEY_LENGTH: ${{ join(secrets.SERVER_SSH_PRIVATE_KEY, '') }} 

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd ${{ secrets.WORK_DIR }}

            echo "🔄 Pulling latest code from repository..."
            git fetch origin master
            git reset --hard origin/master

            echo "🔑 Granting execute permission to deploy script..."
            chmod +x ./deploy.sh

            echo "🚀 Executing deployment script..."
            ./deploy.sh