# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH Secrets
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          echo "User: ${{ secrets.SERVER_USER }}"
          echo "Work Dir: ${{ secrets.WORK_DIR }}"
          echo "Private Key Length: ${{ env.KEY_LENGTH }}"
        env:
          KEY_LENGTH: ${{ join(secrets.SERVER_SSH_PRIVATE_KEY, '') }} 

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}

            echo "Pulling latest code..."
            git pull origin master

            echo "Installing dependencies..."
            /home/ubuntu/.bun/bin/bun install --frozen-lockfile

            echo "Building project..."
            /home/ubuntu/.bun/bin/bun run build

            echo "Restarting application with PM2..."
            /home/ubuntu/.bun/bin/pm2 reload cribelab-website || /home/ubuntu/.bun/bin/pm2 restart cribelab-website