# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.WORK_DIR }}

            echo "Pulling latest code..."
            git pull origin master

            echo "Installing dependencies..."
            bun install --frozen-lockfile

            echo "Building project..."
            bun run build

            echo "Restarting application with PM2..."
            pm2 reload cribelab-website || pm2 restart cribelab-website