# .github/workflows/deploy.yml

name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug SSH Secrets
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          echo "User: ${{ secrets.SERVER_USER }}"
          echo "Work Dir: ${{ secrets.WORK_DIR }}"
          echo "Private Key Length: ${{ env.KEY_LENGTH }}"
        env:
          KEY_LENGTH: ${{ join(secrets.SERVER_SSH_PRIVATE_KEY, '') }} 

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |

            set -e

            BUN_PATH=/home/ubuntu/.bun/bin/bun
            NODE_PATH=/home/ubuntu/.nvm/versions/node/v22.16.0/bin/node
            PM2_PATH=/home/ubuntu/.bun/bin/pm2

            cd ${{ secrets.WORK_DIR }}
            echo "✅ In directory $(pwd)"

            echo "🔄 Pulling latest code..."
            git fetch origin
            git reset --hard origin/master

            echo "📦 Installing dependencies..."
            $BUN_PATH install --frozen-lockfile

            echo "🏗️ Building project..."
            $BUN_PATH run build

            echo "🚀 Restarting application with PM2..."
            APP_NAME="cribelab-website"
            $PM2_PATH delete $APP_NAME || true
            $PM2_PATH start $BUN_PATH --name $APP_NAME -- start

            echo "🎉 Deployment successful!"